# Simple workflow for deploying static content to GitHub Pages
name: Minify static content

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  minify:
    runs-on: ubuntu-latest
    env:
      prepo: ${{github.repository}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Minify Actions
        uses: amireshoon/minifyAction@main
        with:
          repo: $prepo
      - name: Minifying Codes
        run: |
          minifier.sh $prepo
      - name: Pushing to production branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN }}
          directory: github/workspace
          branch: production
          message: Minified css, js and html
          author_name: MinifyAction[bot]
          author_email: minifyAction@users.noreply.github.com
          force: true
